// @title           Flowdo API
// @version         1.0
// @description     A production-ready Flowdo REST API with Hexagonal Architecture.
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.email  support@example.com

// @license.name  MIT

// @host      localhost:8080
// @BasePath  /

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and the JWT token.
package main

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/jmoiron/sqlx"
	_ "github.com/lib/pq"
	"github.com/redis/go-redis/v9"
	"github.com/b1ll1eee/flowdo-api/internal/adapter/inbound/http/handler"
	"github.com/b1ll1eee/flowdo-api/internal/adapter/inbound/http/router"
	"github.com/b1ll1eee/flowdo-api/internal/adapter/outbound/gormrepo"
	"github.com/b1ll1eee/flowdo-api/internal/core/service"
	"github.com/b1ll1eee/flowdo-api/migrations"
	"github.com/b1ll1eee/flowdo-api/pkg/config"
	"github.com/b1ll1eee/flowdo-api/pkg/logger"

	// Side-effect import to register swagger docs generated by swag init.
	_ "github.com/b1ll1eee/flowdo-api/docs"
)

func main() {
	cfg, err := config.Load()
	if err != nil {
		fmt.Fprintf(os.Stderr, "config: %v\n", err)
		os.Exit(1)
	}

	log := logger.New(cfg.App.Environment)

	// ── Auto-migrate ─────────────────────────────────────────────────────────
	{
		db, err := sqlx.Connect("postgres", cfg.Database.DSN)
		if err != nil {
			log.Fatal().Err(err).Msg("open db for migration")
		}
		if err := migrations.Up(db.DB); err != nil {
			log.Fatal().Err(err).Msg("run database migrations")
		}
		db.Close()
		log.Info().Msg("database migrations applied")
	}

	// ── Repository adapters ───────────────────────────────────────────────────
	gdb, err := gormrepo.Open(gormrepo.DBConfig{
		DSN:             cfg.Database.DSN,
		MaxOpenConns:    cfg.Database.MaxOpenConns,
		MaxIdleConns:    cfg.Database.MaxIdleConns,
		ConnMaxLifetime: cfg.Database.ConnMaxLifetime,
		Debug:           cfg.App.Environment == "development",
	})
	if err != nil {
		log.Fatal().Err(err).Msg("connect to postgres (gorm)")
	}
	sqlDB, _ := gdb.DB()
	defer sqlDB.Close()

	userRepo := gormrepo.NewUserRepo(gdb)
	flowdoRepo := gormrepo.NewFlowdoRepo(gdb)
	log.Info().Msg("connected to postgres")

	// ── Redis ─────────────────────────────────────────────────────────────────
	rdb := redis.NewClient(&redis.Options{
		Addr:     cfg.Redis.Addr,
		Password: cfg.Redis.Password,
		DB:       cfg.Redis.DB,
	})
	if err := rdb.Ping(context.Background()).Err(); err != nil {
		log.Warn().Err(err).Msg("redis not reachable — cache disabled")
	} else {
		log.Info().Msg("connected to redis")
	}
	defer rdb.Close()

	// ── Core services ─────────────────────────────────────────────────────────
	authSvc := service.NewAuthService(userRepo, cfg.JWT.Secret, cfg.JWT.TTL)
	flowdoSvc := service.NewFlowdoService(flowdoRepo)

	// ── Inbound adapters (HTTP handlers) ──────────────────────────────────────
	authHandler := handler.NewAuthHandler(authSvc)
	flowdoHandler := handler.NewFlowdoHandler(flowdoSvc)

	// ── Router ────────────────────────────────────────────────────────────────
	r := router.New(log, cfg.App.Environment, cfg.App.CORSOrigins, authSvc, flowdoHandler, authHandler)

	srv := &http.Server{
		Addr:         ":" + cfg.App.Port,
		Handler:      r,
		ReadTimeout:  15 * time.Second,
		WriteTimeout: 15 * time.Second,
		IdleTimeout:  60 * time.Second,
	}

	// ── Graceful shutdown ─────────────────────────────────────────────────────
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)

	go func() {
		log.Info().Str("addr", srv.Addr).Msg("server starting")
		if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			log.Fatal().Err(err).Msg("server error")
		}
	}()

	<-quit
	log.Info().Msg("shutdown signal received")

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	if err := srv.Shutdown(ctx); err != nil {
		log.Error().Err(err).Msg("graceful shutdown failed")
	} else {
		log.Info().Msg("server stopped gracefully")
	}
}
