// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/stretchr/testify/mock"
	"github.com/b1ll1eee/flowdo-api/internal/core/domain"
	"github.com/b1ll1eee/flowdo-api/internal/core/port/outbound"
)

// FlowdoRepository is an autogenerated mock type for the FlowdoRepository interface.
type FlowdoRepository struct {
	mock.Mock
}

func (_m *FlowdoRepository) Save(ctx context.Context, flowdo *domain.Flowdo) error {
	ret := _m.Called(ctx, flowdo)
	return ret.Error(0)
}

func (_m *FlowdoRepository) FindByID(ctx context.Context, id uuid.UUID) (*domain.Flowdo, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.Flowdo
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Flowdo); ok {
		r0 = rf(ctx, id)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*domain.Flowdo)
	}
	return r0, ret.Error(1)
}

func (_m *FlowdoRepository) FindByUserID(ctx context.Context, filter outbound.FlowdoFilter) ([]*domain.Flowdo, int, error) {
	ret := _m.Called(ctx, filter)

	var r0 []*domain.Flowdo
	if rf, ok := ret.Get(0).(func(context.Context, outbound.FlowdoFilter) []*domain.Flowdo); ok {
		r0 = rf(ctx, filter)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]*domain.Flowdo)
	}
	return r0, ret.Int(1), ret.Error(2)
}

func (_m *FlowdoRepository) Update(ctx context.Context, flowdo *domain.Flowdo) error {
	ret := _m.Called(ctx, flowdo)
	return ret.Error(0)
}

func (_m *FlowdoRepository) SoftDelete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)
	return ret.Error(0)
}

func (_m *FlowdoRepository) Reorder(ctx context.Context, userID uuid.UUID, orderedIDs []uuid.UUID) error {
	ret := _m.Called(ctx, userID, orderedIDs)
	return ret.Error(0)
}

// NewFlowdoRepository creates a new instance of FlowdoRepository.
func NewFlowdoRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *FlowdoRepository {
	mock := &FlowdoRepository{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
