// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/stretchr/testify/mock"
	"github.com/b1ll1eee/flowdo-api/internal/core/domain"
)

// UserRepository is an autogenerated mock type for the UserRepository interface.
type UserRepository struct {
	mock.Mock
}

func (_m *UserRepository) Save(ctx context.Context, user *domain.User) error {
	ret := _m.Called(ctx, user)
	return ret.Error(0)
}

func (_m *UserRepository) FindByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.User
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.User); ok {
		r0 = rf(ctx, id)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*domain.User)
	}
	return r0, ret.Error(1)
}

func (_m *UserRepository) FindByEmail(ctx context.Context, email string) (*domain.User, error) {
	ret := _m.Called(ctx, email)

	var r0 *domain.User
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(ctx, email)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*domain.User)
	}
	return r0, ret.Error(1)
}

// NewUserRepository creates a new instance of UserRepository.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
